---
title: "Contact Me"
site-path: "/contact"
format:
  html:
    theme: default
---

The best way to reach me is to send me a connection request and message on [LinkedIn](https://www.linkedin.com/in/sravanivadlamani/). 

You may also use the form below to send me a brief message and I will get back to you as soon as possible! 


<style>
  input[type="text"], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: -12px;
    margin-bottom: 24px;
    resize: vertical;
    font-size: 16px;
  }
  input[type="email"], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: -12px;
    margin-bottom: 24px;
    resize: vertical;
    font-size: 16px;
  }

  button[type="submit"] {
    background-color: green;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    font-size: 24px;
    text-align: center;
  }
  
  input {
    outline: none;
  }

  input:invalid {
    border: solid 1px red;
  }

  input:invalid ~ button {
    background-color: red;
  }
  
  textarea {
    outline: none;
  }

  textarea:invalid {
    border: solid 1px red;
  }

  textarea:invalid ~ button {
    background-color: red;
  }
</style>

<form action="https://getform.io/f/3310d5e0-556a-4a1e-b75e-a1f7fc91fdb5" method="POST">
  <p style="font-size: 24px;">Name<b style="color: red;">*</b></p>
  <input type="text" name="name" required="required"/>
  <p style="font-size: 24px;">Email<b style="color: red;">*</b></p>
  <input type="email" name="email" size="50" required="required"/>
  <p style="font-size: 24px;">Message<b style="color: red;">*</b></p>
  <textarea type="text" name="message" rows="5" cols="50" required="required"></textarea>
  <br>
  <p><em>&ensp;Please note that submitting this form will take you to an external gracias page</em></p>
  <button type="submit">Send</button>
</form>